### PR TITLE
use new vs code solidity plugin from the hardhat team

### PR DESCRIPTION
**Pull request by schmackofant**
We ready to make the leap? 👀

### CODE REVIEW

**Comment by elmariachi111** [comment]
I've been using that initially, switched back to Juan's because it definitely was causing issues I can't remember anymore.

**Comment by elmariachi111** [comment]
So, I'm pretty sure that on my box the hardhat extension isn't resolving the libraries through remappings. Think that worked on my hackathon sample, though. Restarted 3 times. Juan Blanco's extension is disabled.

image

**Comment by schmackofant** [comment]
CleanShot 2023-01-09 at 11 19 13

**Comment by elmariachi111** [comment]
got the same result after a fresh clone / checkout / install. Hardhat plugin is enabled, Juan's extension is disabled, yarn && forge i. Looks like my screenshot. For reproduction reasons: could you do a fresh clone on your box & try again, @schmackofant ? Can you confirm that you've disabled Juan's Solidity extension as well?

**Comment by schmackofant** [comment]
Yes Juan's solidity extension is disabled.

Just did a fresh git clone and forge install, it still works. I get no module errors

**Comment by elmariachi111** [comment]
No, the issue is that my vsc doesn't recognize the library source links (I can't click them). It only highlights the first occurrence it cannot discover. So, you can click on the ERC1155Upgradeable token and it opens files from lib/openzeppelin... for you correctly? Wdym with "hardhat packages"?

**Comment by elmariachi111** [comment]
so, I tried a *lot* now to pinpoint that issue. It indeed seems that the hardhat.config file in side the foundry project. On my machine I can "fix" it by

- removing hardhat.config.js
- shutting down the IDE
- restart the IDE, click 5 times on a dependency.

On my web3 template repo there's not hardhat config, there it works out of the box.

At the moment I'm hesitant to give this an approval because it would definitely break my workflow. Right now, foundry is also (still?) referring to Juan's Solidity extension btw -> https://book.getfoundry.sh/config/vscode. Reason that it works on your box could be that the Mac FS is enumerating file entries differently (and picks up the project config in a different order than on my machine). 

Think, I'm going to post that on the hh extension's issues first so they can reproduce that. Maybe @DorianWilhelm would like to try it on his machine, too? Right now merging this definitely would make my life harder.

**Comment by elmariachi111** [comment]
https://github.com/NomicFoundation/hardhat-vscode/issues/365#issuecomment-1377939072 think we can finalize this soon :)

**Comment by elmariachi111** [comment]
fixed by #55 and #56

**Pull request closed without merging**
